#!/bin/bash

green='\e[1;32m%s\e[0m\n'
gray='\e[1;30m%s\e[0m\n'

printf "$green" "adulting summary"
printf "$gray" "-----------------------------------------------------"
threads --tail
printf "$gray" "-----------------------------------------------------"
printf "\n"
