#!/bin/bash

red='\e[1;31m%s\e[0m\n'
green='\e[1;32m%s\e[0m\n'
yellow='\e[1;33m%s\e[0m\n'
blue='\e[1;34m%s\e[0m\n'
magenta='\e[1;35m%s\e[0m\n'
cyan='\e[1;36m%s\e[0m\n'
gray='\e[1;30m%s\e[0m\n'

printf "$green" "adulting summary"
printf "$gray" "-----------------------------------------------------"
networker 4
printf "$gray" "-----------------------------------------------------"
threads --tail
printf "$gray" "-----------------------------------------------------"
printf "\n"

